---
- name: Deploy web app
  hosts: all
  become: true
  vars:
    app_path: /root
  tasks:
    - name: Copy docker-compose.yml to remote server
      copy:
        src: /root/ansible
        dest: /root
    
    - name: Install Docker and docker-compose
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - docker-compose
    
    - name: Start the application
      #command: "cd /root && docker-compose up -d"
      shell: cd /root/ansible && docker-compose up -d
